### PR TITLE
JSGEN-46 - manifesto

### PR DESCRIPTION
**Pull request by maciejmatu**
- [x] add manifesto page
- [x] add mobile view
- [x] load new font 
- [x] update UI for buttons
- [x] update UI for MapInfo component
- [x] update UI for Navbar
- [x] update UI for Footer

### CODE REVIEW

**Comment by blrhc** [comment]
Looks great. Will need to do a more in-depth review and then we can merge.

**Comment by blrhc** [comment]
@bedeho, ready to merge as far as I'm concerned.

**Comment by maciejmatu** [comment]
@blrhc I added UI fixes, the ones without a check mark are not solved as I need answers to these questions:
- Regarding (1), need an answer for question posted on #52, not sure who should make this decision 😄 
- Regarding (8), could not reproduce missing hero image. Could you check if you can reproduce it?
- Regarding (11), is it okay to use `Math.round` for block height, or should we use `Math.floor`?

Regarding #52:
- [ ] 1. Implementation / Design misalignment regarding Analytics Item - WAITING FOR DECISION
- [x] 2. Updated illustration for homepage
- [x] 3. Changed behaviour for Hero illustrations on screens smaller than 1200px
- [x] 4. Lowered breakpoint for full width button alignment. Now they take full width form 767px
- [x] 5. Fixed top menu
- [x] 6. Unified Announcement Card behaviour on all screen sizes
- [x] 7. Fixed text line break issue (now it occurs only below ~420px)
- [ ] 8. Not sure about the logo issue (it should always be displayed), but I added a container for paragraph text to make it look better for long text. 
- [x] 9. Updated layout for roles headers (make sure it's fine) 

Additional fixes:
- [] 11.Display 'block height' in Analytics section in thousands e.g. `1235k` instead of `1234567`
- [x] 12. Fixed 'What is this' hero button bug, where text is being weirdly shrunk

**Comment by blrhc** [comment]
@maciejmatu Will review and provide answers to your questions on Monday :)

**Comment by blrhc** [comment]
> @maciejmatu Will review and provide answers to your questions on Monday :)

In progress...

**Comment by blrhc** [comment]
@maciejmatu, `math.floor` might be best, but I don't think it matters too much in this case as the function will (as I understand it) return the same thing. Let me know if you disagree!

**Comment by maciejmatu** [comment]
Sure, I'll use `math.floor` 👍

**Comment by blrhc** [comment]
Will review everything else now, but let me know when you've incorporated that :)

**Comment by maciejmatu** [comment]
@blrhc updated it 😄

**Comment by blrhc** [comment]
@maciejmatu Have not checked everything yet, but this is certainly something to take a look at. When the roles page is resized, at certain dimensions we get this effect where the icon is much smaller than the text and misaligned:

resize

**Comment by maciejmatu** [comment]
@blrhc okay I played around with it, and I think I found a good middle-ground. Let me know if it's better now.

**Comment by blrhc** [comment]
Will build now and let you know.

**Comment by blrhc** [comment]
Hi @maciejmatu,

The only other issues I've found are the following:

### Dead Space In Testnet Section
dead space

There's probably too much white space here.

### Misaligned Badges For Roles
misaligned 3
misaligned 2
misaligned maybe
misaligned

Once these are fixed, I will build the site and send to Bedeho for a final review.

**Comment by blrhc** [comment]
@maciejmatu I am satisfied that this is all sorted :)

**Comment by blrhc** [comment]
@bedeho please could you review this PR? I think it is now ready.

**Pull request merged**
