### PR TITLE
JSGEN-45 - rome

### PR DESCRIPTION
**Pull request by maciejmatu**
- Add rome testnet page
- Show testnet on the homepage

I've set launch date to `2019/11/4 11:00`, please make sure that it's correct

### CODE REVIEW

**Comment by maciejmatu** [comment]
Ideally this should be merged after #49 so that I can update test file to include updates introduced there

**Comment by maciejmatu** [comment]
@bedeho this can be reviewed if someone has time 🙂

**Comment by blrhc** [comment]
@maciejmatu Hi again, thanks for this. I have a few points that came up in my review:
- On the homepage, the Rome testnet section is misspelled: `Rome Tesnet`
- Our current working launch date for rome is 18/11/19 (see [here](https://github.com/Joystream/joystream/issues/103)). This needs to be updated on the homepage and `/rome` page.
- On the acropolis page it says `Network Announced`, while on the Rome page it says `Network Live`. This should be the other way around.
- The subtitle/CTA says `Explore available roles and pick the one that suits you the most. Influence the platforms development, while earning Monero in the process.` The grammar should be corrected to  `Explore available roles and pick the one that suits you best. Influence the platform's development and earn Monero in the process.` Also please make sure the text is well aligned (i.e. not like the below).
alignment
- The subtitle of the `Testnet Goals` section says `The goals below is a simplified representation of the Key Results listed in our Release OKR`. It should say `The goals below are a simplified representation of the Key Results listed in our Release OKR.`
- Under the second OKR, the text says `With a Content Directory system that is both built to last, yet still meant to be continuously improved on, it has to be put to use. We will pay for Content Creators to upload a variety of content, and hopefully learn a lot from the result.` This should be replaced with `Rome introduces a Content Cirectory system that is both built to last, yet still meant to be continuously improved on. We will pay for Content Creators to upload a variety of content and we hope to learn a lot from the results.`

**Comment by maciejmatu** [comment]
- Fixed "Testnet" spelling
- Updated launch date to `18/11/19 11:00`
- Fixed wrong network status. Rome is now `announced` and acropolis `live`
- Updated CTA text to have line break between two sentences and fixed grammar
- Updated Testnet Goals text, and unified it across pages
- Updated OKR text

This should cover all of the issues you pointed out above

**Comment by blrhc** [comment]
One more change, please remove the line break `<br>` in the Rome network description on the `Rome` page. Other than that, looks great!

**Comment by blrhc** [comment]
aim
This is how it should look.

**Comment by blrhc** [comment]
There is a similar problem on the roles page. No line break necessary :)

**Comment by blrhc** [comment]
Also on `/acropolis` and `/sparta`

**Comment by blrhc** [comment]
I think we can leave the font as it is, looks quite small now...
The line break was the thing that really needed to be changed

And then with luck we can merge 

🚀

**Comment by blrhc** [comment]
Perfect!

**Comment by blrhc** [comment]
@bwhm Should be ready to merge.

**Pull request merged**
